### ISSUE TITLE
Error for coverage

### ISSUE THREAD

**Issue by ArthurPERE** [DjampaKozlowski/cONTent#4]
Hello,

I have an error for the coverage part, this is my error :

```
Traceback (most recent call last):
  File "/home/tools/cONTent/bin/cONTent.py", line 14, in <module>
    import content.coverage as cvrg
  File "/home/tools/cONTent/content/coverage.py", line 6, in <module>
    sns.set_style("white")
NameError: name 'sns' is not defined. Did you mean: 'sys'?
```

There is a ` import seaborn as sns ` missing.

Regard,
Arthur

**Comment by DjampaKozlowski** [comment]
Issue should be fixed now, thank you for reporting.
